baseURL = "https://jupiterxue.github.io/"
languageCode = "zh-CN"
title = "木夜星空的个人博客"
theme = "cactus"
copyright = "JupiterXue" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts"
weight = 2

[[menu.main]]
name = "归档"
url = "/tags"
weight = 3

[[menu.main]]
name = "关于"
url = "/about"
weight = 4

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "monokai" # 代码配色，默认 dracula。大爱 monokai
tabWidth = 4

[params]

colortheme = "white" # dark, light, white, or classic
rss = true # generate rss feed. default value is false
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = false # default

# 主页配置
description = "东方不亮木星亮，黑了白昼有星空"
mainSection = "posts" # 主要部分
showAllPostsOnHomePage = false # 显示所有文章在主页
postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = true # 显示归档预览
showProjectsList = true # 显示项目列表 (if projects data file exists).
projectsUrl = "https://github.com/JupiterXue" # 项目列表文章标题的链接

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # 日期格式化样式

# 文章页面设置
show_updated = true # 显示更新时间
showReadTime = true # 显示阅读时间

[params.comments]
enabled = false # 显示评论
engine = "disqus" # 评论引擎

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/JupiterXue"
[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/company/github/"
[[params.social]]
name = "email"
link = "839769325@qq.com"  # no need for "mailto:" in the head
