title = "Jupiter 的个人博客"
baseURL = 'https://hba.sid.one/'
#baseURL = 'https://github.com/JupiterXue/JupiterXue.github.io'


# This is what goes in <html lang="">
#languageCode = 'en-us'
languageCode = 'zh-cn'

# This defines how dates are formatted
#defaultContentLanguage = "en-gb"
defaultContentLanguage = "zh-cn"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
theme = "hugo-blog-awesome"

# modern way: pull in theme component as hugo module
#[module]
# Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
# workspace = "hugo-blog-awesome.work"
#[module.hugoVersion]
#extended = true
#min = "0.87.0"
#[[module.imports]]
#path = "github.com/hugo-sid/hugo-blog-awesome"
#disable = false

[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
[services.googleAnalytics]
id = '' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
[services.disqus]
shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2 # ToC starts from H2
endLevel = 4 # ToC ends at H4
ordered = false # generates <ul> instead of <ol>

############################## 中文 ################################
[Languages.zh-cn]
languageName = "中文"
languageCode = "zh-ch"
contentDir = "content/zh-cn"  # 设置根路径位置
#contentDir = "content/en"  # 主页展示文章
#contentDir = "content/arch"  # 主页展示文章
weight = 1

[Languages.zh-cn.menu]
[[Languages.zh-cn.menu.main]]
# The page reference (pageRef) is useful for menu highlighting
# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
pageRef="/"
name = '主页'
url = '/'
weight = 10
[[Languages.zh-cn.menu.main]]
pageRef="posts"
name = '文章'
url = '/posts/'
weight = 20
[[Languages.zh-cn.menu.main]]
pageRef="about"
name = '关于我'
url = '/about/'
weight = 30

[Languages.zh-cn.params]
sitename = "Jupiter `s blog"
defaultColor = "light" # set color mode: dark, light, auto
# You can take a look at layouts/index.html for more information.
description = "Minimal Hugo blog theme with light and dark mode support"
mainSections = ['posts']
toc = true # set to false to disable table of contents 'globally'
tocOpen = false # set to true to open table of contents by default
goToTop = true # set to false to disable 'go to top' button
additionalScripts = ['js/custom.js', 'js/custom-2.js']
# Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
# Your custom scripts will be concatenated to one file `custom.js`.
# When building for production it will be minified.
# The file `custom.js` is loaded on each page (before body tag ends).
dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
# See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
rssFeedDescription = "summary" # available options: 1) summary 2) full
# summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
# full - includes full blog post in the RSS feed. Generated using Hugo .Content .
# By default (or if nothing is specified), summary is used.

[Languages.zh-cn.params.author]
avatar = "木星.png" # put the file in assets folder; also ensure that image has same height and width
#avatar = "Jupiter.jpg" # put the file in assets folder; also ensure that image has same height and width
intro = "Jupiter 的个人博客"
name = "JupiterXue"
description = "东方不亮西方亮✨，黑了白昼有星空🌃"

# Allow to override webmanifest options
[Languages.zh-cn.params.webmanifest]
name = "sitename" # will use "params.sitename" or "title" by default
short_name = "sitename" # same as name
start_url = "/" # will use homepage url by default
theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
display = "standalone"

###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/JupiterXue"

[[params.socialIcons]]
name = "qq"
url = "839769325@qq.com"


